import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { Input } from "@chakra-ui/react";
import { useEffect } from "react";
import { brandsData } from "@/utils/brandsData";

export default function Home() {
  useEffect(()=>{
console.log(brandsData)
  },[])
  return (
    <>
      <Head>
        <title>빌드 검색</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Input
          color="tomato"
          placeholder="ex)그루포"
          _placeholder={{ opacity: 0.4, color: "inherit" }}
        />
        {/* 데이터를 불러오고 데이터가 없으면 스켈레톤을 있으면 BrandCard 컴포넌트 불러오기 */}

      </main>
    </>
  );
}
